i = 1;
j = 1;
y = 0;
size = 120;

HEADER.appendChild(NAVBAR);
NAVBAR.appendChild(MAINLIST);
MAINLIST.setAttribute("id", "menu");

const makelist = () => {
	list = document.createElement("li");
	MAINLIST.appendChild(list);
	list.setAttribute("class", "title");
	number = document.createElement("a");
	list.appendChild(number);
	sublist = document.createElement("ul");
	list.appendChild(sublist);
	if (20 * j <= size) {
		sublistname = padWithLeadingZeros(i,3) + " - " + padWithLeadingZeros(20 * j,3);
	} else {
		sublistname = padWithLeadingZeros(i,3) + " - " + padWithLeadingZeros(size,3);
	}
	number.innerHTML = sublistname;
}
const makeitem = () => {
	switch (i) {
		case 1: radical = "一";
			break;
		case 2: radical = "丨";
			break;
		case 3: radical = "丶";
			break;
		case 4: radical = "丿";
			break;
		case 5: radical = "乙";
			break;
		case 6: radical = "亅";
			break;
		case 7: radical = "二";
			break;
		case 8: radical = "亠";
			break;
		case 9: radical = "人";
			break;
		case 10: radical = "儿";
			break;
		case 11: radical = "入";
			break;
		case 12: radical = "八";
			break;
		case 13: radical = "冂";
			break;
		case 14: radical = "冖";
			break;
		case 15: radical = "冫";
			break;
		case 16: radical = "几";
			break;
		case 17: radical = "凵";
			break;
		case 18: radical = "刀";
			break;
		case 19: radical = "力";
			break;
		case 20: radical = "勹";
			break;
		case 21: radical = "匕";
			break;
		case 22: radical = "匚";
			break;
		case 23: radical = "匸";
			break;
		case 24: radical = "十";
			break;
		case 25: radical = "卜";
			break;
		case 26: radical = "卩";
			break;
		case 27: radical = "厂";
			break;
		case 28: radical = "厶";
			break;
		case 29: radical = "又";
			break;
		case 30: radical = "口";
			break;
		case 31: radical = "囗";
			break;
		case 32: radical = "土";
			break;
		case 33: radical = "士";
			break;
		case 34: radical = "夂";
			break;
		case 35: radical = "夊";
			break;
		case 36: radical = "夕";
			break;
		case 37: radical = "大";
			break;
		case 38: radical = "女";
			break;
		case 39: radical = "子";
			break;
		case 40: radical = "宀";
			break;
		case 41: radical = "寸";
			break;
		case 42: radical = "小";
			break;
		case 43: radical = "尢";
			break;
		case 44: radical = "尸";
			break;
		case 45: radical = "屮";
			break;
		case 46: radical = "山";
			break;
		case 47: radical = "巛";
			break;
		case 48: radical = "工";
			break;
		case 49: radical = "己";
			break;
		case 50: radical = "巾";
			break;
		case 51: radical = "干";
			break;
		case 52: radical = "幺";
			break;
		case 53: radical = "广";
			break;
		case 54: radical = "廴";
			break;
		case 55: radical = "廾";
			break;
		case 56: radical = "弋";
			break;
		case 57: radical = "弓";
			break;
		case 58: radical = "彐";
			break;
		case 59: radical = "彡";
			break;
		case 60: radical = "彳";
			break;
		case 61: radical = "";
			break;
		case 62: radical = "";
			break;
		case 63: radical = "";
			break;
		case 64: radical = "";
			break;
		case 65: radical = "";
			break;
		case 66: radical = "";
			break;
		case 67: radical = "";
			break;
		case 68: radical = "";
			break;
		case 69: radical = "";
			break;
		case 70: radical = "";
			break;
		case 71: radical = "";
			break;
		case 72: radical = "";
			break;
		case 73: radical = "";
			break;
		case 74: radical = "";
			break;
		case 75: radical = "";
			break;
		case 76: radical = "";
			break;
		case 77: radical = "";
			break;
		case 78: radical = "";
			break;
		case 79: radical = "";
			break;
		case 80: radical = "";
			break;
		case 81: radical = "";
			break;
		case 82: radical = "";
			break;
		case 83: radical = "";
			break;
		case 84: radical = "";
			break;
		case 85: radical = "";
			break;
		case 86: radical = "";
			break;
		case 87: radical = "";
			break;
		case 88: radical = "";
			break;
		case 89: radical = "";
			break;
		case 90: radical = "";
			break;
		case 91: radical = "";
			break;
		case 92: radical = "";
			break;
		case 93: radical = "";
			break;
		case 94: radical = "";
			break;
		case 95: radical = "";
			break;
		case 96: radical = "";
			break;
		case 97: radical = "";
			break;
		case 98: radical = "";
			break;
		case 99: radical = "";
			break;
		case 100: radical = "";
			break;
		case 101: radical = "";
			break;
		case 102: radical = "";
			break;
		case 103: radical = "";
			break;
		case 104: radical = "";
			break;
		case 105: radical = "";
			break;
		case 106: radical = "";
			break;
		case 107: radical = "";
			break;/*
		case 108: radical = "";
			break;
		case 109: radical = "";
			break;
		case 110: radical = "";
			break;
		case 111: radical = "";
			break;
		case 112: radical = "";
			break;
		case 113: radical = "";
			break;
		case 114: radical = "";
			break;
		case 115: radical = "";
			break;
		case 116: radical = "";
			break;
		case 117: radical = "";
			break;
		case 118: radical = "";
			break;
		case 119: radical = "";
			break;
		case 120: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;
		case 5: radical = "";
			break;
		case 6: radical = "";
			break;
		case 7: radical = "";
			break;
		case 8: radical = "";
			break;
		case 9: radical = "";
			break;
		case 0: radical = "";
			break;
		case 1: radical = "";
			break;
		case 2: radical = "";
			break;
		case 3: radical = "";
			break;
		case 4: radical = "";
			break;*/
		default:
	}
	menuitem = document.createElement("li");
	menuitem.setAttribute("class", "roll");
	link = document.createElement("a");
	sublist.appendChild(menuitem);
	menuitem.appendChild(link);
	link.setAttribute("href", "../bushu/" + padWithLeadingZeros(i,3) + ".html");
	link.innerHTML = radical + " " +  padWithLeadingZeros(i,3);
	i++;
}
while (i <= size) {
	y++;
	if (y == 1) {
		makelist();
		j++;
	}
	makeitem(i);
	if (y == 20) {
		y = 0;
	}
}
