i = 1;
j = 1;
y = 0;
size = 214;

HEADER.appendChild(NAVBAR);
NAVBAR.appendChild(MAINLIST);
MAINLIST.setAttribute("id", "menu");

const makelist = () => {
	list = document.createElement("li");
	MAINLIST.appendChild(list);
	list.setAttribute("class", "title");
	number = document.createElement("a");
	list.appendChild(number);
	sublist = document.createElement("ul");
	list.appendChild(sublist);
	if (20 * j <= size) {
		sublistname = padWithLeadingZeros(i,3) + " - " + padWithLeadingZeros(20 * j,3);
	} else {
		sublistname = padWithLeadingZeros(i,3) + " - " + padWithLeadingZeros(size,3);
	}
	number.innerHTML = sublistname;
}
const makeitem = () => {
	switch (i) {
		case 1: radical = "一";
			break;
		case 2: radical = "丨";
			break;
		case 3: radical = "丶";
			break;
		case 4: radical = "丿";
			break;
		case 5: radical = "乙";
			break;
		case 6: radical = "亅";
			break;
		case 7: radical = "二";
			break;
		case 8: radical = "亠";
			break;
		case 9: radical = "人";
			break;
		case 10: radical = "儿";
			break;
		case 11: radical = "入";
			break;
		case 12: radical = "八";
			break;
		case 13: radical = "冂";
			break;
		case 14: radical = "冖";
			break;
		case 15: radical = "冫";
			break;
		case 16: radical = "几";
			break;
		case 17: radical = "凵";
			break;
		case 18: radical = "刀";
			break;
		case 19: radical = "力";
			break;
		case 20: radical = "勹";
			break;
		case 21: radical = "匕";
			break;
		case 22: radical = "匚";
			break;
		case 23: radical = "匸";
			break;
		case 24: radical = "十";
			break;
		case 25: radical = "卜";
			break;
		case 26: radical = "卩";
			break;
		case 27: radical = "厂";
			break;
		case 28: radical = "厶";
			break;
		case 29: radical = "又";
			break;
		case 30: radical = "口";
			break;
		case 31: radical = "囗";
			break;
		case 32: radical = "土";
			break;
		case 33: radical = "士";
			break;
		case 34: radical = "夂";
			break;
		case 35: radical = "夊";
			break;
		case 36: radical = "夕";
			break;
		case 37: radical = "大";
			break;
		case 38: radical = "女";
			break;
		case 39: radical = "子";
			break;
		case 40: radical = "宀";
			break;
		case 41: radical = "寸";
			break;
		case 42: radical = "小";
			break;
		case 43: radical = "尢";
			break;
		case 44: radical = "尸";
			break;
		case 45: radical = "屮";
			break;
		case 46: radical = "山";
			break;
		case 47: radical = "巛";
			break;
		case 48: radical = "工";
			break;
		case 49: radical = "己";
			break;
		case 50: radical = "巾";
			break;
		case 51: radical = "干";
			break;
		case 52: radical = "幺";
			break;
		case 53: radical = "广";
			break;
		case 54: radical = "廴";
			break;
		case 55: radical = "廾";
			break;
		case 56: radical = "弋";
			break;
		case 57: radical = "弓";
			break;
		case 58: radical = "彐";
			break;
		case 59: radical = "彡";
			break;
		case 60: radical = "彳";
			break;
		case 61: radical = "心"; 
			break;
		case 62: radical = "戈";
			break;
		case 63: radical = "戶";
			break;
		case 64: radical = "手";
			break;
		case 65: radical = "支";
			break;
		case 66: radical = "攴";
			break;
		case 67: radical = "文";
			break;
		case 68: radical = "斗";
			break;
		case 69: radical = "斤";
			break;
		case 70: radical = "方";
			break;
		case 71: radical = "无";
			break;
		case 72: radical = "日";
			break;
		case 73: radical = "曰";
			break;
		case 74: radical = "月";
			break;
		case 75: radical = "木";
			break;
		case 76: radical = "欠";
			break;
		case 77: radical = "止";
			break;
		case 78: radical = "歹";
			break;
		case 79: radical = "殳";
			break;
		case 80: radical = "毋";
			break;
		case 81: radical = "比";
			break;
		case 82: radical = "毛";
			break;
		case 83: radical = "氏";
			break;
		case 84: radical = "气";
			break;
		case 85: radical = "水";
			break;
		case 86: radical = "火";
			break;
		case 87: radical = "爪";
			break;
		case 88: radical = "父";
			break;
		case 89: radical = "爻";
			break;
		case 90: radical = "爿";
			break;
		case 91: radical = "片";
			break;
		case 92: radical = "牙";
			break;
		case 93: radical = "牛";
			break;
		case 94: radical = "犬";
			break;
		case 95: radical = "玄";
			break;
		case 96: radical = "玉";
			break;
		case 97: radical = "瓜";
			break;
		case 98: radical = "瓦";
			break;
		case 99: radical = "甘";
			break;
		case 100: radical = "生";
			break;
		case 101: radical = "用";
			break;
		case 102: radical = "田";
			break;
		case 103: radical = "疋";
			break;
		case 104: radical = "疒";
			break;
		case 105: radical = "癶";
			break;
		case 106: radical = "白";
			break;
		case 107: radical = "皮";
			break;
		case 108: radical = "皿";
			break;
		case 109: radical = "目";
			break;
		case 110: radical = "矛";
			break;
		case 111: radical = "矢";
			break;
		case 112: radical = "石";
			break;
		case 113: radical = "示";
			break;
		case 114: radical = "禸";
			break;
		case 115: radical = "禾";
			break;
		case 116: radical = "穴";
			break;
		case 117: radical = "立";
			break;
		case 118: radical = "竹";
			break;
		case 119: radical = "米";
			break;
		case 120: radical = "糸";
			break;
		case 121: radical = "缶";
			break;
		case 122: radical = "网";
			break;
		case 123: radical = "羊";
			break;
		case 124: radical = "羽";
			break;
		case 125: radical = "老";
			break;
		case 126: radical = "而";
			break;
		case 127: radical = "耒";
			break;
		case 128: radical = "耳";
			break;
		case 129: radical = "聿";
			break;
		case 130: radical = "肉";
			break;
		case 131: radical = "臣";
			break;
		case 132: radical = "自";
			break;
		case 133: radical = "至";
			break;
		case 134: radical = "臼";
			break;
		case 135: radical = "舌";
			break;
		case 136: radical = "舛";
			break;
		case 137: radical = "舟";
			break;
		case 138: radical = "艮";
			break;
		case 139: radical = "色";
			break;
		case 140: radical = "艸";
			break;
		case 141: radical = "虍";
			break;
		case 142: radical = "虫";
			break;
		case 143: radical = "血";
			break;
		case 144: radical = "行";
			break;
		case 145: radical = "衣";
			break;
		case 146: radical = "襾";
			break;
		case 147: radical = "見";
			break;
		case 148: radical = "角";
			break;
		case 149: radical = "言";
			break;
		case 150: radical = "谷";
			break;
		case 151: radical = "豆";
			break;
		case 152: radical = "豕";
			break;
		case 153: radical = "豸";
			break;
		case 154: radical = "貝";
			break;
		case 155: radical = "赤";
			break;
		case 156: radical = "走";
			break;
		case 157: radical = "足";
			break;
		case 158: radical = "身";
			break;
		case 159: radical = "車";
			break;
		case 160: radical = "辛";
			break;
		case 161: radical = "辰";
			break;
		case 162: radical = "辵";
			break;
		case 163: radical = "邑";
			break;
		case 164: radical = "酉";
			break;
		case 165: radical = "釆";
			break;
		case 166: radical = "里";
			break;
		case 167: radical = "金";
			break;
		case 168: radical = "長";
			break;
		case 169: radical = "門";
			break;
		case 170: radical = "阜";
			break;
		case 171: radical = "隶";
			break;
		case 172: radical = "隹";
			break;
		case 173: radical = "雨";
			break;
		case 174: radical = "靑";
			break;
		case 175: radical = "非";
			break;
		case 176: radical = "面";
			break;
		case 177: radical = "革";
			break;
		case 178: radical = "韋";
			break;
		case 179: radical = "韭";
			break;
		case 180: radical = "音";
			break;
		case 181: radical = "頁";
			break;
		case 182: radical = "風";
			break;
		case 183: radical = "飛";
			break;
		case 184: radical = "食";
			break;
		case 185: radical = "首";
			break;
		case 186: radical = "香";
			break;
		case 187: radical = "馬";
			break;
		case 188: radical = "骨";
			break;
		case 189: radical = "高";
			break;
		case 190: radical = "髟";
			break;
		case 191: radical = "鬥";
			break;
		case 192: radical = "鬯";
			break;
		case 193: radical = "鬲";
			break;
		case 194: radical = "鬼";
			break;
		case 195: radical = "魚";
			break;
		case 196: radical = "鳥";
			break;
		case 197: radical = "鹵";
			break;
		case 198: radical = "鹿";
			break;
		case 199: radical = "麥";
			break;
		case 200: radical = "麻";
			break;
		case 201: radical = "黃";
			break;
		case 202: radical = "黍";
			break;
		case 203: radical = "黑";
			break;
		case 204: radical = "黹";
			break;
		case 205: radical = "黽";
			break;
		case 206: radical = "鼎";
			break;
		case 207: radical = "鼓";
			break;
		case 208: radical = "鼠";
			break;
		case 209: radical = "鼻";
			break;
		case 210: radical = "齊";
			break;
		case 211: radical = "齒";
			break;
		case 212: radical = "龍";
			break;
		case 213: radical = "龜";
			break;
		case 214: radical = "龠";
			break;
		default:
	}
	menuitem = document.createElement("li");
	menuitem.setAttribute("class", "roll");
	link = document.createElement("a");
	sublist.appendChild(menuitem);
	menuitem.appendChild(link);
	link.setAttribute("href", "../bushu/" + padWithLeadingZeros(i,3) + ".html");
	link.innerHTML = radical + " " +  padWithLeadingZeros(i,3);
	i++;
}
while (i <= size) {
	y++;
	if (y == 1) {
		makelist();
		j++;
	}
	makeitem();
	if (y == 20) {
		y = 0;
	}
}
